select * from funcionarios;
select * from departamentos;
select * from localizacao;

/* FUNCOES DE AGREGACAO */

/* QUERY SIMPLES */

SELECT * FROM FUNCIONARIOS;

/* CONTANDO O NUMERO DE OCORRENCIAS */

SELECT COUNT(*) FROM FUNCIONARIOS;
SELECT COUNT(*) FROM DEPARTAMENTOS;
SELECT COUNT(*) FROM LOCALIZACAO;

/* AGRUPANDO POR SEXO COM GROUP BY */

SELECT COUNT(*) FROM FUNCIONARIOS
GROUP BY SEXO;

/* COLOCANDO O NOME DA COLUNA */

SELECT SEXO, COUNT(*) AS "QTD_POR_SEXO" FROM FUNCIONARIOS
GROUP BY SEXO;

/* MOSTRANDO O NUMERO DE FUNCIONARIOS EM CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, COUNT(*) AS "FUNC_POR_DEPART"
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO; 

/* EXIBINDO O MAXIMO DE SALARIOS = 149929 */

SELECT MAX(SALARIO) AS "MAIOR_SALARIO" 
FROM FUNCIONARIOS;

/* EXIBINDO O MINIMO DE SALARIO = 40138 */

SELECT MIN(SALARIO) AS "MENOR_SALARIO" 
FROM FUNCIONARIOS;

/* EXIBINDO O MAXIMO E O MINIMO JUNTOS */

SELECT MIN(SALARIO) AS "MENOR_SALARIO", MAX(SALARIO) AS "MAIOR_SALARIO" 
FROM FUNCIONARIOS;

/* EXIBINDO O MAXIMO E O MINIMO DE CADA DEPARTAMENTO */

SELECT DEPARTAMENTO, MIN(SALARIO) AS "min_salario", MAX(SALARIO) AS "max_salario", 
	   (MAX(SALARIO) - MIN(SALARIO)) AS "dif_salario"
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* EXIBINDO O MAXIMO E O MINIMO POR SEXO */

SELECT SEXO, MIN(SALARIO) AS "min_salario", MAX(SALARIO) AS "max_salario", 
	   (MAX(SALARIO) - MIN(SALARIO)) AS "dif_salario"
FROM FUNCIONARIOS
GROUP BY SEXO;

/* ESTATISTICAS */

/* MOSTRANDO UMA QUANTIDADE LIMITADA DE LINHAS */

SELECT * FROM FUNCIONARIOS
LIMIT 10;

/* QUAL O GASTO TOTAL DE SALARIO PAGO PELA EMPRESA */

SELECT SUM(SALARIO) AS "TOTAL_SAL"
FROM FUNCIONARIOS;

/* QUAL O MONTANTE TOTAL QUE CADA DEPARTAMENTO RECEBE DE SALARIO */

SELECT DEPARTAMENTO, SUM(SALARIO) AS "SUM_SALARIO"
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* POR DEPARTAMENTO, QUAL O TOTAL E A MÉDIA PAGA PARA OS FUNCIONARIOS? */

SELECT SUM(SALARIO), AVG(SALARIO)
FROM FUNCIONARIOS;

SELECT DEPARTAMENTO, SUM(SALARIO) AS "SUM_SALARIO", AVG(SALARIO) AS "AVG_SALARIO"
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

/* ORDENANDO */

SELECT DEPARTAMENTO, SUM(SALARIO) AS "SUM_SALARIO", AVG(SALARIO) AS "AVG_SALARIO"
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 3;

SELECT DEPARTAMENTO, SUM(SALARIO) AS "SUM_SALARIO", AVG(SALARIO) AS "AVG_SALARIO"
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 3 ASC;Q

SELECT DEPARTAMENTO, SUM(SALARIO) AS "SUM_SALARIO", AVG(SALARIO) AS "AVG_SALARIO"
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 2 DESC;

SELECT * FROM FUNCIONARIOS;

SELECT DEPARTAMENTO, COUNT(*) AS "QTD_FUNC", AVG(SALARIO) AS "AVG_SALARIO"
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 2;

/* Modelagem Banco de Dados x Data Science */

/* Banco de Dados -> 1,2 e 3 Formas normais
Evitam redundancia, consequentemente poupam espaço em disco.
Consomem muito processamento em função de Joins. Queries lentas
*/

/*
Data Sciente e B.I -> Focam em agregações e performance. Não
se preocupam com espço em disco. Em B.I., modelgem minima (DW)
em Data Sciente, preferencialmente modelagem Colunar
*/

/*
O SERVIDOR DE MAQUINAS GEROU UM ARQUIVO DE LOG CSV.
VAMOS IMPORTA-LO E ANALISA-LO DENTRO DO NOSSO BANCO
*/

/* IMPORTANDO O CSV */

CREATE TABLE MAQUINAS(
	MAQUINA VARCHAR(20),
	DIA INT,
	QTD NUMERIC(10,2)
);

COPY MAQUINAS
FROM 'C:\LogMaquinas.csv'
DELIMITER ','
CSV HEADER;

SELECT * FROM MAQUINAS;

/* QUAL A MEDIA DE CADA MAQUINA */

SELECT MAQUINA, AVG(QTD) AS "MEDIA_QTD"
FROM MAQUINAS
GROUP BY MAQUINA;

/* ARREDONDANDO */
--ROUND(COLUNA,2)

SELECT MAQUINA, SUM(QTD) AS "QTD TOTAL", ROUND(AVG(QTD),2) AS "MEDIA_QTD"
FROM MAQUINAS
GROUP BY MAQUINA
ORDER BY 3 DESC;

/* QUAL A MODA DAS QUANTIDADES */

SELECT MAQUINA, QTD, COUNT(*) AS "MODA"
FROM maquinas
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC;

/* QUAL A MODA DAS QUANTIDADES DE CADA MAQUINA */

SELECT MAQUINA, QTD, COUNT(*) AS "MODA"
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 01'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

SELECT MAQUINA, QTD, COUNT(*) AS "MODA"
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 02'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

SELECT MAQUINA, QTD, COUNT(*) AS "MODA"
FROM MAQUINAS
WHERE MAQUINA = 'Maquina 03'
GROUP BY MAQUINA, QTD
ORDER BY 3 DESC
LIMIT 1;

/* MODA DO DATASET INTEIRO */

SELECT QTD, COUNT(*) AS "MODA"
FROM MAQUINAS
GROUP BY QTD
ORDER BY 2 DESC;

/* QUAL O MAXIMO E MINIMO E AMPLITUDE DE CADA MAQUINA */

SELECT MAQUINA,
	   MAX(QTD) AS MAXIMO,
	   MIN(QTD) AS MINIMO,
	   (MAX(QTD) - MIN(QTD)) AS AMPLITUDE
	   FROM MAQUINAS
	   GROUP BY MAQUINA
	   ORDER BY 4 DESC;

/* ACRESCENTANDO A MEDIA AO RELATORIO */

SELECT MAQUINA,
	   MAX(QTD) AS MAXIMO,
	   MIN(QTD) AS MINIMO,
	   (MAX(QTD) - MIN(QTD)) AS "amplitude",
	   ROUND(AVG(QTD),2) AS "media"
	   FROM MAQUINAS
	   GROUP BY MAQUINA
	   ORDER BY 3 DESC;
	   
/* DESVIOI PADRAO E VARIANCIA */

--STDDEV_POP(COLUNA)
--VAR_POP(COLUNA)

SELECT MAQUINA,
	   MAX(QTD) AS MAXIMO,
	   MIN(QTD) AS MINIMO,
	   (MAX(QTD) - MIN(QTD)) AS "amplitude",
	   ROUND(AVG(QTD),2) AS "media",
	   ROUND(STDDEV_POP(QTD),2) AS "desvio_pad",
	   ROUND(VAR_POP(QTD),2) AS "variancia"
	   FROM MAQUINAS
	   GROUP BY MAQUINA
	   ORDER BY 3 DESC;
	   