/* PRIMEIRA FORMA NORMAL */

 /* COLUNAS = CAMPOS, LINHAS = REGISTROS
 
 1 - TODO CAMPO VETORIZADO (ELEMENTOS DA MESMA FAMILIA) SE TORNARA OUTRA TABELA = NESSE EXEMPLO, O TELEFONE
 
 [AMARELO, AZUL, LARANJA, VERDE] -> CORES
 [KA, FIESTA, UNO, CIVIC] -> CARROS
 
 2 - TODO CAMPO MULTIVALORADO SE TORNARA OUTRA TABELA
 QUANDO O CAMPO FOR DIVISIVEL (ELEMENTOS DE FAMILIA DIFERENTE) = NESSE EXEMPLO, O ENDERECO
 
 3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE 
 TODO O REGISTRO COMO SENDO UNICO.
 ISSO É O QUE CHAMAMOS DE PRIMARY KEY
 
 */
 
 /* CARDINALIDADE */
 
 /* QUEM DEFINE A CARDINALIDADE É A REGRA DE NEGÓCIOS */

/* 

 PRIMEIRO ALGORISMO - OBRIGATORIEDADE
 0 - NAO OBRIGATÓRIO
 N - OBRIGATÓRIO
 
 SEGUNDO ALGORISMO - CARDINALIDADE
 1 - MAXIMO DE UM
 N - MAIS DE UM
 
 LÊ-SE DE ACORDO COM O SEGUNDO ALGORISMO 
 1,1 = 1 PRA 1
 1,N = 1 PRA MUITOS
 
 */
 
 CREATE DATABASE COMERCIO;
 
 USE COMERCIO;
 
 SHOW DATABASES;
 
 CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL, /*O ENUM SO EXISTE NO MYSQL*/
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE 
 );
 
 --UNIQUE = AQUI O UNIQUE DEFINE O RELACIONAMENTO 1 X 1
 
 CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
 );
 
 CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
 );
 
 DROP TABLE CLIENTE;
 
 /* 
	ENDERECO - OBRIGATORIO
	CADASTRO DE SOMENTE UM.
	
	TELEFONE - NAO OBRIGATORIO
	CADASTRO DE MAIS DE UM (OPCIONAL)
 */
 
 /* FOREIGN KEY */
 
 /*
	CHAVE ESTRANGEIRA É A CHAVE PRIMARIA DE UMA TABELA
	QUE VAI ATÉ A OUTRA TABELA PARA FAZER REFERENCIA ENTRE
	REGISTROS
 */
 
/* TABELA MAIS FRACA OU MAIS FORTE DEPENDE DA REGRA DE NEGOCIO */
	
/* EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTO 1 X N A CHAVE ESTRANGEIRA FICARA SEMPRE NA CARDINAALIDADE N */

/* CONSTRAINT = REGRA */