/*
Criar um banco de dados chamado oficina e conectar-se a ele
Fazer a seguinte modelagem:

Sr José quer modernizar a oficina, e por enquanto, quer cadastrar os carros que entram
para realizar serviços e os seus respectivos donos. Sr José mencionou que cada cliente possui apenas um carro.
Um carro possui uma marca. Sr José também quer saber as cores dos carros para ter ideia de qual tinta comprar, 
e informa que um carro pode ter mais de uma cor. Sr José necessita armazenar os telefones dos clientes, mas nao
quer que eles sejam obrigatorios.

*/

CREATE DATABASE OFICINA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL','RES','COM') NOT NULL,
	NUMERO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE,
	ID_MARCA INT	
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO,ID_COR)
);

ALTER TABLE  CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

INSERT INTO MARCA VALUES(NULL,'');

INSERT INTO CARRO VALUES(NULL,'');

INSERT INTO CLIENTE VALUES(NULL,'');

INSERT INTO TELEFONE VALUES(NULL,'');

INSERT INTO COR VALUES(NULL,'');



SELECT * FROM CARRO;
SELECT * FROM CLIENTE;
SELECT * FROM TELEFONE;
SELECT * FROM COR;
