/*PSQL NO ORACLE*/

--DATA:
--CHAMADO:
--SOLICITANTE:
--OBJETIVO:

SELECT * FROM DICT;

--USUARIO DO BANCO DE DADOS

SHOW USER;

--TABELA DUMMY - IDIOTA
--TUDO DO ORACLE TEM QUE VIR DE ALGUM LUGAR
--ENTAO SELECT 1 + 1; APENAS NAO VAI FUNCIONAR

SELECT 1 + 1 AS SOMA FROM DUAL; --SEMPRE QUE EU QUISER 
--FAZER UM SELECT QUE NAO EXISTE TABELA, A ORIGEM É A TABELA DUAL

SELECT 1 + 1 FROM DUAL;

SELECT 1 + 1, 'SOMA' FROM DUAL;

/* VERIFICANDO O AMBIENTE */
-- B023 -> 32 BITS
-- B0047 -> 64 BITS

SELECT METADATA FROM SYS.KOPM$;

--DICIONARIO DE DADOS

SELECT * FROM DICT;

-- INSTANCIA UNICA OU INTANCIA RAC
--EU ESTOU UTILIZANDO PARALELISMO?

SELECT PARALLEL FROM V$INSTANCE; 

--ESTRUTURAS DE MEMORIA

SELECT COMPONENT, CURRENT_SIZE, MIN_SIZE, MAX_SIZE
FROMO V$SGA_DYNAMIC_COMPONENTS;

--CONECTANDO A OUTRO BANCO DE DADOS

SQLPLUS SYSTETM/SENHA@NOMEDOBANCO
ORACLE_SID=XE

--NOME DO BANCO DE DADOS

SELECT NAME FROM V$DATABASE;

--VERSAO DO BANCO DE DADOS

SELECT BANNER FROM V$VERSION;

--VERIFICIANDO PRIVILEGIOS DOS USUARIOS

SELECT * FROM USER_SYS_PRIVS;

--TABELAS DO USUARIO

SELECT TABLE_NAME FROM USER_TABLES;

