/* PROCEDURES */

-- SP_ STORE PROCEDURE

CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK (SEXO IN('M','F')), --ENUM DO MYSQL = CHECK NO SQL SERVER
	MASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE TEL(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK ( TIPO IN('CEL','COM')),
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

ALTER TABLE TEL ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

INSERT INTO PESSOA VALUES('ANTONIO','M','1981-02-13')
INSERT INTO PESSOA VALUES('DANIEL','M','1985-03-18')
INSERT INTO PESSOA VALUES('CLEIDE','F','1979-10-13')
INSERT INTO PESSOA VALUES('MAFRA','M','1981-02-13')
INSERT INTO PESSOA VALUES('JBS','F','1981-02-13')

SELECT @@IDENTITY -- GUARDA O ULTIMO IDENTITY INSERIDO NA SEÇÃO
GO

SELECT * FROM PESSOA

INSERT INTO TEL VALUES('CEL','9879008',1)
INSERT INTO TEL VALUES('COM','8757909',1)
INSERT INTO TEL VALUES('CEL','9875890',2)
INSERT INTO TEL VALUES('CEL','9347689',2)
INSERT INTO TEL VALUES('COM','2998689',3)
INSERT INTO TEL VALUES('COM','2098978',2)
INSERT INTO TEL VALUES('CEL','9008679',3)
GO

/* CRIANDO A PROCEDURE */

CREATE PROC SOMA 
AS
	SELECT 10 + 10 AS 'SOMA'
GO

/* EXECUÇÃO DA PROCEDURE */

SOMA

EXEC SOMA
GO

/* PROCEDURES DINAMICAS = COM PARAMETROS */

CREATE PROC CONTA @NUM1 INT, @NUM2 INT
AS
	SELECT @NUM1 + @NUM2 AS 'RESULTADO'
GO

EXEC CONTA 1,2
GO

/* APAGANDO A PROCEDURE */

DROP PROC CONTA
GO

/* PROCEDURES EM TABELAS */

SELECT NOME, NUMERO
FROM PESSOA
INNER JOIN TEL
ON IDPESSOA = ID_PESSOA
WHERE TIPO = 'CEL'
GO

/* TRAZER OS TELEFONES DE ACORDO COM O TIPO PASSADO */
CREATE PROC TELEFONES @TIPO CHAR(3)
AS
	SELECT NOME, NUMERO
	FROM PESSOA
	INNER JOIN TEL
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO = @TIPO
GO

SELECT * FROM PESSOA
SELECT * FROM TEL
GO

EXEC TELEFONES 'CEL'
GO

EXEC TELEFONES 'COM'
GO

/* PARAMETROS DE OUTPUT */

SELECT TIPO, COUNT(*) AS 'QUANTIDADE'
FROM TEL
GROUP BY TIPO
GO

/* CRIANDO PROCEDURE COM PARAMETROS DE ENTRADA E PARAMENTRO DE SAIDA */

CREATE PROC GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TEL
	WHERE TIPO = @TIPO
	GO

/* EXECUCAO DA PROC COM PARAMETRO DE SAIDA */

/* TRANSACTION SQL -> LINGUAGEM QUE O SQL SERVER TRABALHA */

DECLARE @SAIDA INT
EXEC GETTIPO @TIPO = 'CEL', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA
GO

DECLARE @SAIDA INT
EXEC GETTIPO 'CEL', @SAIDA OUTPUT
SELECT @SAIDA
GO

/* PROCEDURE DE CADASTRO */

CREATE PROC CADASTRO @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE,
@TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
	DECLARE @FK INT 

	INSERT INTO PESSOA VALUES(@NOME,@SEXO,@NASCIMENTO)

	SET @FK = (SELECT IDPESSOA FROM PESSOA
		       WHERE IDPESSOA = @@IDENTITY)

	INSERT INTO TEL VALUES(@TIPO, @NUMERO, @FK)
GO

EXEC CADASTRO 'JORGE','M','1981-01-01','CEL','972278322'
GO

SELECT * FROM PESSOA
SELECT * FROM TEL
GO

SELECT PESSOA.*, TEL.*
FROM PESSOA
INNER JOIN TEL
ON IDPESSOA = ID_PESSOA;
GO

SELECT @@IDENTITY -- GUARDA O ULTIMO IDENTITY INSERIDO NA SEÇÃO
GO