/*
Criar um banco de dados chamado oficina e conectar-se a ele
Fazer a seguinte modelagem:

Sr José quer modernizar a oficina, e por enquanto, quer cadastrar os carros que entram
para realizar serviços e os seus respectivos donos. Sr José mencionou que cada cliente possui apenas um carro.
Um carro possui uma marca. Sr José também quer saber as cores dos carros para ter ideia de qual tinta comprar, 
e informa que um carro pode ter mais de uma cor. Sr José necessita armazenar os telefones dos clientes, mas nao
quer que eles sejam obrigatorios.

*/

CREATE DATABASE OFICINA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL','RES','COM') NOT NULL,
	NUMERO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE,
	ID_MARCA INT	
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY(ID_CARRO,ID_COR)
);

ALTER TABLE  CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

INSERT INTO MARCA VALUES(NULL,'JEEP');
INSERT INTO MARCA VALUES(NULL,'HONDA');
INSERT INTO MARCA VALUES(NULL,'TOYOTA');
INSERT INTO MARCA VALUES(NULL,'FORD');
INSERT INTO MARCA VALUES(NULL,'FERRARI');
INSERT INTO MARCA VALUES(NULL,'BMW');
INSERT INTO MARCA VALUES(NULL,'FIAT');
INSERT INTO MARCA VALUES(NULL,'VOLVO');
INSERT INTO MARCA VALUES(NULL,'NISSAN');
INSERT INTO MARCA VALUES(NULL,'RENAULT');

INSERT INTO CARRO VALUES(NULL,'2019','XXX-7777',1);
INSERT INTO CARRO VALUES(NULL,'2020','AAA-1111',2);
INSERT INTO CARRO VALUES(NULL,'2021','BBB-2222',1);
INSERT INTO CARRO VALUES(NULL,'2020','CCC-1212',3);
INSERT INTO CARRO VALUES(NULL,'2010','DDD-3232',4);
INSERT INTO CARRO VALUES(NULL,'2005','TTT-4545',5);
INSERT INTO CARRO VALUES(NULL,'2001','WWW-6161',5);
INSERT INTO CARRO VALUES(NULL,'2018','LLL-5555',9);
INSERT INTO CARRO VALUES(NULL,'2015','YYY-6588',7);
INSERT INTO CARRO VALUES(NULL,'2000','BBU-0101',6);

SELECT * 
FROM MARCA
ORDER BY 1;

SELECT C.IDCARRO, C.MODELO, C.PLACA, M.MARCA
FROM CARRO C
INNER JOIN MARCA M
ON C.ID_MARCA = M.IDMARCA;


INSERT INTO CLIENTE VALUES(NULL,'JAMILE', 'F',1);
INSERT INTO CLIENTE VALUES(NULL,'GUILHERME', 'M',2);
INSERT INTO CLIENTE VALUES(NULL,'SIMONE', 'F',3);
INSERT INTO CLIENTE VALUES(NULL,'JUDAS', 'M',4);
INSERT INTO CLIENTE VALUES(NULL,'MATEUS', 'M',5);
INSERT INTO CLIENTE VALUES(NULL,'ALDA', 'F',6);
INSERT INTO CLIENTE VALUES(NULL,'CAMILA', 'F',7);
INSERT INTO CLIENTE VALUES(NULL,'ANA', 'F',8);
INSERT INTO CLIENTE VALUES(NULL,'JOAO', 'M',9);
INSERT INTO CLIENTE VALUES(NULL,'RODRIGO', 'M',10);

SELECT C.IDCARRO, C.MODELO, C.PLACA, CLI.NOME, CLI.SEXO, M.MARCA
FROM CARRO C
INNER JOIN MARCA M
ON C.ID_MARCA = M.IDMARCA
INNER JOIN CLIENTE CLI
ON C.IDCARRO = CLI.ID_CARRO
WHERE SEXO = 'F';

INSERT INTO TELEFONE VALUES(NULL,'RES','3313-6169',1);
INSERT INTO TELEFONE VALUES(NULL,'CEL','8891-2125',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','3361-6633',2);
INSERT INTO TELEFONE VALUES(NULL,'COM','9875-2123',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','9968-7152',2);
INSERT INTO TELEFONE VALUES(NULL,'RES','3365-8984',7);
INSERT INTO TELEFONE VALUES(NULL,'RES','9632-6585',8);
INSERT INTO TELEFONE VALUES(NULL,'CEL','9917-5522',7);
INSERT INTO TELEFONE VALUES(NULL,'COM','9966-8855',6);
INSERT INTO TELEFONE VALUES(NULL,'COM','9931-7458',3);
INSERT INTO TELEFONE VALUES(NULL,'CEL','9933-4144',3);

SELECT C.IDCARRO, C.MODELO, C.PLACA, M.MARCA, CLI.NOME, CLI.SEXO, T.NUMERO,T.TIPO
FROM CARRO C
INNER JOIN MARCA M
ON C.ID_MARCA = M.IDMARCA
INNER JOIN CLIENTE CLI
ON C.IDCARRO = CLI.ID_CARRO
INNER JOIN TELEFONE T
ON CLI.IDCLIENTE = T.ID_CLIENTE;

SELECT CLI.IDCLIENTE,CLI.NOME, T.NUMERO
FROM CLIENTE CLI
INNER JOIN TELEFONE T
ON CLI.IDCLIENTE = T.ID_CLIENTE;

INSERT INTO COR VALUES(NULL,'AZUL');
INSERT INTO COR VALUES(NULL,'VERDE');
INSERT INTO COR VALUES(NULL,'AMARELO');
INSERT INTO COR VALUES(NULL,'ROSA');
INSERT INTO COR VALUES(NULL,'BRANCO');
INSERT INTO COR VALUES(NULL,'CINZA');
INSERT INTO COR VALUES(NULL,'VERMELHO');
INSERT INTO COR VALUES(NULL,'ROXO');

SELECT * FROM CARRO;
SELECT * FROM CLIENTE;
SELECT * FROM TELEFONE;
SELECT * FROM COR;

INSERT INTO CARRO_COR VALUES(1,3);
INSERT INTO CARRO_COR VALUES(1,1);
INSERT INTO CARRO_COR VALUES(2,3);
INSERT INTO CARRO_COR VALUES(3,2);
INSERT INTO CARRO_COR VALUES(4,3);
INSERT INTO CARRO_COR VALUES(5,4);
INSERT INTO CARRO_COR VALUES(6,5);
INSERT INTO CARRO_COR VALUES(7,5);
INSERT INTO CARRO_COR VALUES(8,3);
INSERT INTO CARRO_COR VALUES(9,2);
INSERT INTO CARRO_COR VALUES(9,4);
INSERT INTO CARRO_COR VALUES(10,7);
INSERT INTO CARRO_COR VALUES(10,6);
